#TEST
os: osx
language: java
jdk:
    - openjdk11
osx_image: xcode11.3

before_install:
    - gem install package_cloud
  
script:
    - package_cloud push alchen/test-next /test.deb
    # - package_cloud repository create travisci_test